"""add_created_at_in_tokens

Revision ID: 8c464c3d23aa
Revises: e5d2611330ed
Create Date: 2024-01-22 18:32:48.982359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c464c3d23aa'
down_revision: Union[str, None] = 'e5d2611330ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'updated_at')
    op.drop_column('tokens', 'created_at')
    # ### end Alembic commands ###
